########################### COMMON SETTINGS

x-common-default: &common-default
    security_opt:
        - no-new-privileges:true
    restart: unless-stopped

########################### SERVICES
services:
    rendezvous:
        <<: *common-default
        container_name: screensy-rendezvous
        build: ./screensy-rendezvous

    website:
        <<: *common-default
        container_name: screensy-website
        build: ./screensy-website

    caddy:
        <<: *common-default
        image: caddy:2.8.4
        container_name: screensy-caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./Caddyfile:/etc/caddy/Caddyfile"

    turn:
        <<: *common-default
        image: coturn/coturn:4.6.2
        container_name: screensy-turn
        # Use the host network directly as Docker performs badly with large port ranges.
        network_mode: host
        volumes:
            - "./turnserver.conf:/etc/coturn/turnserver.conf"
